 create table Role (
        id bigint generated by default as identity unique,
        name varchar(255),
        primary key (id)
    );

    create table User (
        id bigint generated by default as identity unique,
        city varchar(255),
        state varchar(255),
        street varchar(255),
        streetNumber varchar(255),
        zipcode integer,
        addressCardNumber varchar(255),
        addressCardPicture binary(255),
        certified bit,
        idCardNumber varchar(255),
        idCardPicture binary(255),
        enabled bit,
        password varchar(255),
        email varchar(255),
        employee bit,
        employer bit,
        facebookValidatedId varchar(255),
        firstName varchar(255),
        introduction varchar(255),
        lastName varchar(255),
        phoneNumber varchar(255),
        profileImagePath varchar(255),
        providerId varchar(255),
        userName varchar(255) unique,
        primary key (id)
    );
    
     create table JobCategory (
        id bigint generated by default as identity unique,
        main bit not null,
        name varchar(255),
        main_id bigint,
        primary key (id)
    );

    create table User_Roles (
        user_id bigint not null,
        role_id bigint not null,
        primary key (user_id, role_id)
     
    );

    create table ValueSet (
        id bigint generated by default as identity unique,
        name varchar(255),
        valuesString varchar(255),
        primary key (id)
    );

    create table ValueStore (
        id bigint generated by default as identity unique,
        name varchar(255),
        value varchar(255),
        primary key (id)
    );

    create table settlement (
        id bigint generated by default as identity unique,
        settlement varchar(255),
        zip integer,
        primary key (id)
    );

