insert into settlement (id ,zip, settlement) values (1, 2000,'Szentendre');
insert into settlement (id, zip, settlement) values (2, 2009,'Pilisszentlászló');
insert into settlement (id, zip, settlement) values (3, 2011,'Budakalász');
insert into settlement (id, zip, settlement) values (4, 2013,'Pomáz ');
insert into settlement (id, zip, settlement) values (5, 2014,'Csobánka');
insert into settlement (id, zip, settlement) values (6, 2015,'Szigetmonostor');
insert into settlement (id, zip, settlement) values (7, 2016,'Leányfalu');
insert into settlement (id, zip, settlement) values (8, 2017,'Pócsmegyer');
insert into settlement (id, zip, settlement) values (9, 2021,'Tahitótfalu');
insert into settlement (id, zip, settlement) values (10, 2022,'Tahitótfalu');
insert into settlement (id, zip, settlement) values (11, 2023,'Dunabogdány');
insert into settlement (id, zip, settlement) values (12, 2024,'Kisoroszi');
insert into settlement (id, zip, settlement) values (13, 2025,'Visegrád ');
insert into settlement (id, zip, settlement) values (14, 2026,'Visegrád ');
insert into settlement (id, zip, settlement) values (15, 2027,'Dömös');
insert into settlement (id, zip, settlement) values (16, 2028,'Pilismarót');
insert into settlement (id, zip, settlement) values (17, 2030,'Érd');
insert into settlement (id, zip, settlement) values (18, 2035,'Érd');