create table Role (
    id bigint generated by default as identity unique,
    name varchar(255),
    primary key (id)
);

create table User (
    id bigint generated by default as identity unique,
    enabled bit,
    password varchar(255),
    userName varchar(255) unique,
    primary key (id)
);

create table User_Roles (
    user_id bigint not null,
    role_id bigint not null,
    primary key (user_id, role_id)
);

alter table User_Roles 
    add constraint FKE8518549583644E2 
    foreign key (role_id) 
    references Role;

alter table User_Roles 
    add constraint FKE8518549FD6108C2 
    foreign key (user_id) 
    references User;
    
insert into Role (id, name) values (1, 'USER_ROLE');
insert into User (id, enabled, password, userName) values (1, 1, '82b9a701f55b9a48c6083f247beea5c1', 'aacs');
insert into User_Roles (user_id, role_id) values (1, 1);

