PrimeFaces.locales ['hu'] = {
    closeText: 'Kész',
    prevText: 'Előző',
    nextText: 'Következő',
    monthNames: ['Január', 'Február', 'Március', 'Április', 'Május', 'Június', 'Július', 'Augusztus', 'Szeptember', 'Október', 'November', 'December' ],
    monthNamesShort: ['Jan', 'Febr', 'Márc', 'Ápr', 'Máj', 'Júni', 'Júli', 'Aug', 'Szept', 'Okt', 'Nov', 'Dec' ],
    dayNames: ['Vasárnap', 'Hétfő', 'Kedd', 'Szerda', 'Csütörtök', 'Péntek', 'Szombat'],
    dayNamesShort: ['Va', 'Hé', 'Ke', 'Sze', 'Csüt', 'Pén', 'Szo'],
    dayNamesMin: ['V', 'H', 'K', 'Sze ', 'Cs', 'P ', 'Szo'],
    weekHeader: 'Hét',
    firstDay: 1,
    isRTL: false,
    showMonthAfterYear: true,
    yearSuffix:'',
    timeOnlyTitle: 'Csak idő',
    timeText: 'Idő',
    hourText: 'Óra',
    minuteText: 'Perc',
    secondText: 'Másodperc',
    currentText: 'Most',
    ampm: false,
    month: 'Hónap',
    week: 'Hét',
    day: 'Nap',
    allDayText: 'Egész nap'
};